version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: whatsapp_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
  networks:
      - proxy
      - default
  labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.bot-secure.entrypoints=websecure"
      - "traefik.http.routers.bot-secure.rule=Host(`bot.africandao.com`)"
      - "traefik.http.routers.bot-secure.service=bot-service"
      - "traefik.http.services.bot-service.loadbalancer.server.port=5000"


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: whatsapp_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres


  redis:
    image: redis:6

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    networks:
      - default
    image: whatsapp_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    networks:
      - default
    image: whatsapp_production_celerybeat
    command: /start-celerybeat

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    networks:
      - default
    image: whatsapp_production_flower
    command: /start-flower

networks:
  proxy:
    external: true
