# Generated by Django 4.0.8 on 2022-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='cypherspot', max_length=255, verbose_name='Name of User'),
        ),
    ]
